name: Build

on:
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: CGO_ENABLED=0 go build -o vault-plugin-secrets-cloudflare cmd/cloudflare/main.go

    - name: Test
      run: CGO_ENABLED=0 go test ./...
